/** Native DSH tokens, with separate summary, detail, and conversation surfaces. */
export const CSS = `
.dsh-task-inline,.dsh-task-panel,.dsh-task-review-note{color:var(--dsw-alias-label-primary);font:13px/1.55 system-ui,sans-serif}
.dsh-task-inline *,.dsh-task-panel *{box-sizing:border-box}
.dsh-task-inline{container-type:inline-size;flex:none;width:calc(100% - 2 * var(--dsh-composer-side-clearance,16px) - 4 * var(--dsh-composer-dock-inset,8px));max-width:calc(var(--dsh-composer-card-max-width,800px) - 4 * var(--dsh-composer-dock-inset,8px));margin:6px auto;border-radius:12px;background:var(--dsw-specific-menu,var(--dsw-alias-bg-layer-1));box-shadow:var(--dsw-elevation-panel);border:1px solid var(--dsw-alias-border-l1);overflow:hidden}
.dsh-task-inline-head{display:flex;align-items:center;gap:10px;padding:9px 12px}.dsh-task-inline-head strong{font-weight:550}.dsh-task-inline-head span{color:var(--dsw-alias-label-secondary);white-space:nowrap;font-size:12px}.dsh-task-inline-head button{margin-left:auto;flex-shrink:0}
.dsh-task-inline-summary{display:flex;gap:12px;align-items:center;padding:0 12px 10px}.dsh-task-inline-copy{flex:1;min-width:0}.dsh-task-inline-copy p{margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dsh-task-inline-copy small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--dsw-alias-label-secondary)}
.dsh-task-panel{height:100%;min-height:0;display:flex;flex-direction:column;background:var(--dsw-alias-bg-layer-1)}
.dsh-task-panel-header{flex:none;padding:16px 18px 0;border-bottom:1px solid var(--dsw-alias-border-l1)}.dsh-task-panel h2{font-size:15px;font-weight:600;margin:0}.dsh-task-status{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:8px 0 12px;color:var(--dsw-alias-label-secondary);font-size:12px}
.dsh-task-tabs{display:flex;gap:20px}.dsh-task-tabs button{border:0;border-bottom:2px solid transparent;padding:9px 0;background:none;color:var(--dsw-alias-label-secondary);font:inherit;cursor:pointer}.dsh-task-tabs button[aria-selected=true]{border-bottom-color:var(--dsw-alias-brand-primary);color:var(--dsw-alias-label-primary);font-weight:600}
.dsh-task-body{flex:1;min-height:0;overflow:auto;padding:16px 18px;overscroll-behavior:contain}.dsh-task-chat-body{flex:1;min-height:0;display:flex;flex-direction:column;overflow:hidden}.dsh-task-panel [hidden]{display:none!important}
.dsh-task-panel h3{font-size:12px;font-weight:600;color:var(--dsw-alias-label-secondary);margin:0 0 10px}.dsh-task-section+.dsh-task-section{margin-top:20px}.dsh-task-section p{margin:7px 0;overflow-wrap:anywhere}.dsh-task-section summary{cursor:pointer;padding:7px 0}.dsh-task-section small{color:var(--dsw-alias-label-tertiary)}
.dsh-task-objective{white-space:pre-wrap;overflow-wrap:anywhere}.dsh-task-muted{color:var(--dsw-alias-label-secondary)}.dsh-task-meta{font-size:11px;color:var(--dsw-alias-label-tertiary)}
.dsh-task-card{border:1px solid var(--dsw-alias-border-l1);border-radius:12px;padding:14px;background:var(--dsw-alias-bg-layer-2);overflow-wrap:anywhere}.dsh-task-card ul{padding-left:18px;margin:8px 0}.dsh-task-card li+li{margin-top:10px}.dsh-task-card h4{font-size:14px;margin:0 0 8px;font-weight:600}
.dsh-task-actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.dsh-task-footer{flex:none;display:flex;align-items:center;flex-wrap:wrap;gap:8px;padding:12px 18px;border-top:1px solid var(--dsw-alias-border-l1);background:var(--dsw-alias-bg-layer-1)}
.dsh-task-button{font:inherit;line-height:1.5;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:6px 11px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);cursor:pointer;white-space:nowrap}.dsh-task-button:hover{background:var(--dsw-alias-bg-layer-3)}.dsh-task-button[data-action=off]{color:var(--dsw-alias-label-secondary)}.dsh-task-button:disabled{opacity:.45;cursor:default}.dsh-task-button:focus-visible,.dsh-task-tabs button:focus-visible{outline:2px solid var(--dsw-alias-label-secondary);outline-offset:3px}
.dsh-task-link{border:0;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;padding:3px 0;font:inherit;font-size:12px;white-space:nowrap}.dsh-task-link:hover{color:var(--dsw-alias-label-primary);text-decoration:underline}.dsh-task-error{color:var(--dsw-alias-state-error-primary);padding:0 16px;overflow-wrap:anywhere}.dsh-task-review{white-space:pre-wrap;overflow-wrap:anywhere}
.dsh-task-review-note{display:flex;gap:10px;align-items:flex-start;margin:12px 0;padding:10px 0;border-top:1px solid var(--dsw-alias-border-l1)}.dsh-task-review-note .dsh-task-review-copy{flex:1;min-width:0}.dsh-task-review-note strong{font-size:12px;font-weight:550}.dsh-task-review-note p{margin:4px 0 0;color:var(--dsw-alias-label-secondary);font-size:13px}.dsh-task-dot{width:7px;height:7px;border-radius:50%;background:var(--dsw-alias-state-success-primary);flex:none;margin-top:7px}.dsh-task-dot[data-verdict=revise],.dsh-task-dot[data-verdict=needs-user]{background:var(--dsw-alias-state-warn-primary)}
.dsh-task-consultation{flex:1;min-height:0;display:flex;flex-direction:column;overflow:hidden}.dsh-task-consultation-hint{flex:none;padding:10px 16px;font-size:12px;color:var(--dsw-alias-label-secondary);border-bottom:1px solid var(--dsw-alias-border-l1)}.dsh-task-consultation-hint p{margin:0}.dsh-task-consultation-content{flex:1;min-height:0;position:relative;display:flex;flex-direction:column}.dsh-task-empty{padding:20px;color:var(--dsw-alias-label-secondary)}
@container(max-width:480px){.dsh-task-inline-head{gap:7px;flex-wrap:wrap}.dsh-task-inline-summary{align-items:flex-start;flex-wrap:wrap}.dsh-task-inline-copy{flex-basis:100%}}
`
