/** Native DSH tokens, with separate summary, detail, and conversation surfaces. */
export const CSS = `
.dsh-task-inline,.dsh-task-panel,.dsh-task-review-note{color:var(--dsw-alias-label-primary);font-size:var(--dsh-content-font-size-secondary,13px);line-height:1.55;font-family:inherit}
.dsh-task-inline *,.dsh-task-panel *{box-sizing:border-box}
.dsh-task-inline{container-type:inline-size;flex:none;width:calc(100% - 2 * var(--dsh-composer-side-clearance,16px) - 4 * var(--dsh-composer-dock-inset,8px));max-width:calc(var(--dsh-composer-card-max-width,800px) - 4 * var(--dsh-composer-dock-inset,8px));margin:6px auto;border-radius:12px;background:var(--dsw-specific-menu,var(--dsw-alias-bg-layer-1));backdrop-filter:var(--dsw-menu-backdrop-filter);box-shadow:var(--dsw-elevation-panel);border:0;overflow:hidden;--dsw-elevation-stroke-color:var(--dsw-alias-border-l1)}
.dsh-task-inline-head{display:flex;align-items:center;gap:8px;padding:7px 12px}.dsh-task-overview-toggle{flex:1;min-width:0}.dsh-task-overview-status{margin-left:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--dsw-alias-label-tertiary);font-size:12px}.dsh-task-inline-head>button{flex:none}
.dsh-task-inline-map{padding:0 10px}.dsh-task-participants{display:flex;align-items:center;gap:2px;flex-wrap:wrap;padding:4px 0;color:var(--dsw-alias-label-secondary);font-size:11px}.dsh-task-participants>span{padding:0 8px 0 3px}.dsh-task-participants button{color:var(--dsw-alias-label-secondary)}.dsh-task-inline-controls{display:flex;justify-content:flex-end;padding:4px 10px 8px;border-top:1px solid var(--dsw-alias-border-l1)}
.dsh-task-inline-summary{display:flex;gap:12px;align-items:center;padding:2px 14px 6px}.dsh-task-inline-copy{flex:1;min-width:0}.dsh-task-inline-copy p{margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dsh-task-inline-copy small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--dsw-alias-label-secondary)}
.dsh-task-panel{height:100%;min-height:0;display:flex;flex-direction:column;background:var(--dsw-alias-bg-layer-1)}
.dsh-task-panel-header{flex:none;padding:0 16px;border-bottom:1px solid var(--dsw-alias-border-l1)}.dsh-task-panel-navigation{display:flex;align-items:center;justify-content:space-between;gap:8px}.dsh-task-panel-heading{display:flex;align-items:center;justify-content:space-between;gap:12px}.dsh-task-panel h2{font-size:15px;font-weight:600;margin:0}.dsh-task-status{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:4px 0 8px;color:var(--dsw-alias-label-secondary);font-size:12px}
.dsh-task-tabs{display:flex;gap:20px}.dsh-task-tabs button{border:0;border-bottom:2px solid transparent;padding:9px 0;background:none;color:var(--dsw-alias-label-secondary);font:inherit;cursor:pointer}.dsh-task-tabs button[aria-selected=true]{border-bottom-color:var(--dsw-alias-brand-primary);color:var(--dsw-alias-label-primary);font-weight:600}
.dsh-task-body{flex:1;min-height:0;overflow:auto;padding:16px 18px;overscroll-behavior:contain}.dsh-task-chat-body{flex:1;min-height:0;display:flex;flex-direction:column;overflow:hidden}.dsh-task-panel [hidden]{display:none!important}
.dsh-task-history-item{display:flex;flex-direction:column;align-items:flex-start;gap:3px;width:100%;margin:0;padding:12px 0;border:0;border-top:1px solid var(--dsw-alias-border-l1);background:transparent;color:inherit;text-align:left;font:inherit;cursor:pointer}.dsh-task-history-item:hover{color:var(--dsw-alias-brand-primary)}.dsh-task-history-item:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:1px}.dsh-task-history-item strong{font-weight:550}.dsh-task-history-item small{color:var(--dsw-alias-label-secondary)}
.dsh-task-panel h3{font-size:12px;font-weight:600;color:var(--dsw-alias-label-secondary);margin:0 0 10px}.dsh-task-section+.dsh-task-section{margin-top:20px}.dsh-task-section p{margin:7px 0;overflow-wrap:anywhere}.dsh-task-section summary{cursor:pointer;padding:7px 0}.dsh-task-section small{color:var(--dsw-alias-label-tertiary)}
.dsh-task-objective{white-space:pre-wrap;overflow-wrap:anywhere}.dsh-task-muted{color:var(--dsw-alias-label-secondary)}.dsh-task-meta{font-size:11px;color:var(--dsw-alias-label-tertiary)}
.dsh-task-card{border-top:1px solid var(--dsw-alias-border-l1);padding:16px 0 0;overflow-wrap:anywhere}.dsh-task-card ul{padding-left:18px;margin:8px 0}.dsh-task-card li+li{margin-top:10px}.dsh-task-card h4{font-size:14px;margin:0 0 8px;font-weight:600}
.dsh-task-actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.dsh-task-footer{flex:none;display:flex;align-items:center;flex-wrap:wrap;gap:8px;padding:12px 18px;border-top:1px solid var(--dsw-alias-border-l1);background:var(--dsw-alias-bg-layer-1)}
.dsh-task-tabs button:hover{color:var(--dsw-alias-label-primary)}.dsh-task-tabs button:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}
.dsh-task-disclosure{margin:4px 0}.dsh-task-disclosure [data-disclosure-row]{min-height:30px;border-radius:6px;padding:2px 4px}.dsh-task-disclosure [data-disclosure-row]:hover{background:var(--dsw-alias-interactive-bg-hover)}.dsh-task-disclosure [data-disclosure-row]:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:1px}.dsh-task-disclosure-title{flex:1!important;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dsh-task-disclosure-content{padding:2px 4px 8px 26px;color:var(--dsw-alias-label-secondary)}
.dsh-task-error{color:var(--dsw-alias-state-error-primary);padding:0 16px;overflow-wrap:anywhere}.dsh-task-review{white-space:pre-wrap;overflow-wrap:anywhere}
.dsh-task-review-note{display:flex;gap:10px;align-items:flex-start;margin:12px 0;padding:10px 0;border-top:1px solid var(--dsw-alias-border-l1)}.dsh-task-review-note .dsh-task-review-copy{flex:1;min-width:0}.dsh-task-review-note strong{font-size:12px;font-weight:550}.dsh-task-review-note p{margin:4px 0 0;color:var(--dsw-alias-label-secondary);font-size:13px}.dsh-task-dot{width:7px;height:7px;border-radius:50%;background:var(--dsw-alias-state-success-primary);flex:none;margin-top:7px}.dsh-task-dot[data-verdict=revise],.dsh-task-dot[data-verdict=needs-user]{background:var(--dsw-alias-state-warn-primary)}
.dsh-task-consultation{flex:1;min-height:0;display:flex;flex-direction:column;overflow:hidden}.dsh-task-consultation-content{flex:1;min-height:0;width:100%;position:relative;display:flex;flex-direction:column}.dsh-task-consultation-content>*{flex:1;min-width:0;min-height:0;height:100%}.dsh-task-consultation-content [data-composer-seat]{margin-top:auto}.dsh-task-empty{padding:20px;color:var(--dsw-alias-label-secondary)}
.dsh-task-draft-link{flex:none;border:0;background:none;color:var(--dsw-alias-label-secondary);text-align:left;font:inherit;font-size:12px;padding:6px 16px;cursor:pointer;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dsh-task-draft-link:hover{color:var(--dsw-alias-brand-primary)}.dsh-task-draft{margin:12px 0;padding:12px 0;border-top:1px solid var(--dsw-alias-border-l1)}.dsh-task-draft p{white-space:pre-wrap;margin:4px 0}.dsh-task-draft-actions{display:flex;gap:10px;align-items:center}.dsh-task-draft small{font-size:11px;color:var(--dsw-alias-label-secondary)}.dsh-task-fault{padding:12px;border-radius:8px;background:var(--dsw-alias-bg-layer-2);margin-bottom:16px}.dsh-task-fault p{font-size:12px;overflow-wrap:anywhere}.dsh-task-evidence-chat{margin-bottom:12px}.dsh-task-log-record{white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px;margin:4px 0;max-height:320px;overflow:auto}
.dsh-task-repair-form{display:flex;flex-direction:column;gap:10px;margin-top:12px}.dsh-task-repair-form>label{display:flex;flex-direction:column;gap:6px}.dsh-task-repair-form fieldset{display:flex;flex-direction:column;gap:8px;border:0;padding:0;margin:0}.dsh-task-repair-form legend{margin-bottom:6px;color:var(--dsw-alias-label-secondary)}
@container(max-width:380px){.dsh-task-overview-status{margin-left:6px;font-size:11px}.dsh-task-inline-head{gap:2px;padding-inline:8px}}

.dsh-task-review-phases { display: flex; flex-wrap: wrap; gap: 6px 16px; padding: 0; list-style: none; color: var(--fg-muted, #888); font-size: 12px; }
.dsh-task-review-phases li[aria-current="step"] { color: var(--fg, inherit); font-weight: 600; }
`
